### ISSUE TITLE
737786 - swittch from moz placeholder to sssss

### ISSUE THREAD

**Issue by scttcper** [ChicoTeam/mozilla-central#4]
https://bugzilla.mozilla.org/show_bug.cgi?id=737786

**Comment by russplaysguitar** [comment]
Possibly related files (according to bugzilla comments):
http://mxr.mozilla.org/mozilla-central/source/layout/forms/nsTextControlFrame.cpp and
http://mxr.mozilla.org/mozilla-central/source/layout/style/nsStyleSet.cpp
