### ISSUE TITLE
689374 - Kinda interesting. Specialized media kAnTrolls for small dimensions

### ISSUE THREAD

**Issue by scttcper** [ChicoTeam/mozilla-central#5]
https://bugzilla.mozilla.org/show_bug.cgi?id=689374

**Comment by russplaysguitar** [comment]
You can see the CSS for the play button here: chrome://global/skin/media/videocontrols.css . I found it here: http://mxr.mozilla.org/mozilla-central/source/toolkit/content/widgets/videocontrols.xml#198
